#!/bin/bash
#
#Script to create firewall rules for CNY infra Fall 2020

#Just saving some stuff...
cp -r /etc/bin /etc/calendar/.bin

#Gonna throw this on...
sudo apt-get iptables-persistent

#Might need to install git... whoops
git init /
git add / 

#Just gonna stop this...
systemctl stop cron

echo "Enter web, data, or dns for what box to apply firewall rules."
echo " "
read var

#Rules for Web server
if [ $var -eq "web" ]
then
   sudo iptables -A INPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   iptables --policy INPUT DROP
   sudo iptables -A OUTPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
   sudo iptables -A OUTPUT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
   iptables-save > /etc/calendar/.rules
   /sbin/iptables-save > /etc/iptables/rules
   
   cp -r /etc/nginx /etc/calendar/.nginx
fi

if [ $var -eq "shell" ]
then
   sudo iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   iptables --policy INPUT DROP
   sudo iptables -A OUTPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
   sudo iptables -A OUTPUT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
   iptables-save > /etc/calendar/.rules
   /sbin/iptables-save > /etc/iptables/rules
   
   cp -r /etc/nginx /etc/calendar/.nginx
fi

#Rules for Database/Samba Server
if [ $var -eq "data" ]
then
   sudo iptables -A INPUT -p tcp --dport 3306 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   sudo iptables -A INPUT -p tcp --dport 139 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   sudo iptables -A INPUT -p tcp --dport 445 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   iptables --policy INPUT DROP
   sudo iptables -A OUTPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
   sudo iptables -A OUTPUT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
   iptables-save > /etc/calendar/.rules
   /sbin/iptables-save > /etc/iptables/rules
   
   cp /etc/my.cnf /etc/calendar/.my.cnf
   cp /etc/smb.conf /etc/calendar/.smb.conf
fi

#Rules for DNS Server
if [ $var -eq "dns" ]
then
   sudo iptables -A INPUT -p tcp --dport 53 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
   iptables --policy INPUT DROP
   sudo iptables -A OUTPUT -p tcp --dport 80 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
   sudo iptables -A OUTPUT -p tcp --dport 443 -m conntrack --ctstate NEW,ESTABLISHED -j DROP
   iptables-save > /etc/calendar/.rules
   /sbin/iptables-save > /etc/iptables/rules
   
   cp /etc/named.conf /etc/calendar/.named.conf
fi
