#!/bin/bash

#Script will create a backup of a file and then send it out to multiple directories in a list...
#and everytime a backup is inserted into the original file it will be comared to a "golden backup".
#If the golden backup and the current backup comparing match it will then upload.

#golden backup is stored within the script and hidden somewhere in the system

#Creates the etc_dir array which has all /etc/ directories
etc_dir=()
while IFS= read -r line;
do
	etc_dir+=("$line")
done < <(ls -d /etc/*/)

#Create Golden Backup and hides it in /etc/fonts as hidden
echo "Enter the filepath for backup"
read back_path
echo ""
#Gets name for backup
echo What service are you backing up?
read serv
cp $back_path /etc/fonts/.golden_back$serv
#back="$(<"$back_path")"
back=$(cat $back_path)
echo ""

#Puts the backup in all etc directories for redundancy
count=0
for i in "${etc_dir[@]}"
do
	cp $back_path $i/.back${serv}_${count}
	echo Backup was copied to $i
	echo ""
	count=$(expr $count + 1)
done

#Chooses a random backup file and copares it to golden backup, then copies the backup...
#into the original file. Will also alert administrator on tty if something has changed.
while true;
do
echo ""
ran=$(echo $(($RANDOM % (${#etc_dir[@]}+1))))
current=$(cat $back_path)
	if [[ $current == $back ]]
	then
		echo Config file is still correct
		echo ""
	else
		echo Config file is not correct.
		echo $serv config file has been changed! > /dev/tty2
		current_back=$(cat ${etc_dir[$ran]}.back${serv}_${ran})
		if [[ $current_back == $back ]]
		then
			echo Backup number $ran is still good.
			cp ${etc_dir[$ran]}/.back${serv}_${ran} $back_path
			echo The config file has been updated
			echo ""
		else
			echo Backup number $ran not good
			echo $serv backup number $ran has been changed! > /dev/tty2
			echo $back > ${etc_dir[$ran]}/.back${serv}_${ran}
			cp ${etc_dir[$ran]}/.back${serv}_${ran} $back_path
			echo The config file has been updated
			echo ""
		fi
	fi
echo "Waiting 30 seconds for next check"
sleep 30
done

echo done

