#!/usr/bin/python3.6

import socket

def netcat(hostname, port, content):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((hostname, port))
    s.sendall(content)
    s.shutdown(socket.SHUT_WR)
    int = 1
    while int = 1:
        data = s.recv(1024)
        if data == "":
            break
        print "Received:", repr(data)
        int = 2
    print "Connection closed."
    s.close()
